#!/usr/bin/env bash
set -euo pipefail
source infra/env.sh
: "${TENANT_ID:?}" "${API_APP_ID:?set in infra/env.sh}" "${INVENTORY_APP_ID:?set in infra/env.sh}"
az config set extension.use_dynamic_install=yes_without_prompt -o none   # app-insights commands are an extension
APPI_CS=$(az monitor app-insights component show -g "$RG" -a "$APPI" --query connectionString -o tsv 2>/dev/null || echo "")

REDIS_HOST=$(az redisenterprise show -g "$RG" -n "$REDIS" --query hostName -o tsv 2>/dev/null || echo "")
SQL_HOST="${SQL_SERVER}.database.windows.net"

sql() {  # $1 database name
  echo "Server=tcp:${SQL_HOST},1433;Database=$1;Authentication=Active Directory Default;Encrypt=True;"
}

cat > deploy/helm/values/azure.generated.yaml <<EOF
# GENERATED by deploy/scripts/write-azure-values.sh — do not edit by hand.
# Contains hostnames only. There are no secrets in this file, by design (ADR-0011).

image:
  registry: "${ACR}.azurecr.io"
  pullPolicy: IfNotPresent

ingress:
  className: "webapprouting.kubernetes.azure.com"

environment: production

env:
  # Azure Monitor. Not a secret: local auth is disabled on the resource, so this string alone
  # can't send anything — each pod authenticates with its managed identity.
  APPLICATIONINSIGHTS_CONNECTION_STRING: "${APPI_CS}"

  # SQL: Entra token via Workload Identity — no password
  ConnectionStrings__orderflow-orders: "$(sql orderflow-orders)"
  ConnectionStrings__orderflow-inventory: "$(sql orderflow-inventory)"
  ConnectionStrings__orderflow-payments: "$(sql orderflow-payments)"
  ConnectionStrings__orderflow-notifications: "$(sql orderflow-notifications)"

  # Kafka protocol -> Event Hubs, SASL/OAUTHBEARER with an Entra token
  ConnectionStrings__kafka: "${EH_NS}.servicebus.windows.net:9093"
  Kafka__AuthMode: "AzureAd"
  Kafka__ProvisionTopics: "false"
  # Event Hubs Standard rejects compressed Kafka batches ("Message format on broker does not
  # support request"). The payloads are small JSON, so compression buys almost nothing.
  Kafka__CompressionType: "None"

  # Redis with Entra ID (only Order reads it)
  Redis__HostName: "${REDIS_HOST:+${REDIS_HOST}:10000}"

  # Service Bus (only Notification reads it)
  ServiceBus__FullyQualifiedNamespace: "${SB_NS}.servicebus.windows.net"

  # Entra ID token validation. Identifiers only — the signing keys come from Entra's metadata.
  AzureAd__Instance: "https://login.microsoftonline.com/"
  AzureAd__TenantId: "${TENANT_ID}"
  AzureAd__ClientId: "${API_APP_ID}"                          # gateway + order: audience orderflow-api
  Inventory__TokenScope: "api://${INVENTORY_APP_ID}/.default" # only Order reads it

# Ingress-only default deny per pod; each service's values file lists who may connect (3N).
networkPolicy:
  enabled: true
EOF

echo "Wrote deploy/helm/values/azure.generated.yaml"